baseURL = 'https://blog.claytondavis.dev/'
languageCode = 'en-us'
title = 'Clayton Davis Blog'


[params]
	subtitle = "The blog of an overly opinionated cloud consultant"
    description = 'The blog of an overly opinionated cloud consultant'
    images = ['/images/BlogLogo.png']

	# Optional 64x64 avatar image.
	avatar = "/images/circle_bw_HeadShot.png"

	# Content types to disable Disqus on.
	disableDisqusTypes = ["page"]
	
	featherIconsCDN = true

	mode = "dark" # "dark" or "auto"

    # Google Analytics 4
    googleAnalyticsID = "G-7HBR1XK054"

# Nav.
[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "About"
url = "/about/index.html"
weight = 2

[[menu.main]]
name = "Resume"
url = "https://resume.claytondavis.dev/"
weight = 3

[[params.social]]
name = "LinkedIn"
icon = "linkedin"
url = "https://www.linkedin.com/in/clayton-davis-17723239/"
